<?php 
/* auto-generated by nettl */ 
define('DB_HOST', 'nettl-dbinstance-01.cxpdols1ngq4.eu-west-1.rds.amazonaws.com');
define('DB_USER', 'asialiveaboard4');
define('DB_NAME', 'asialiveaboard4');
define('DB_PASSWORD', 'fafb6dbb5ab5d4b8');

// We call this manually for each site to ensure it always runs.
define('DISABLE_WP_CRON', true);

//define('WP_PROXY_HOST', '10.0.1.6');
//define('WP_PROXY_PORT', '3128');
//define('WP_PROXY_USERNAME', '');
//define('WP_PROXY_PASSWORD', '');
//define('WP_PROXY_BYPASS_HOSTS', 'localhost');

define('WP_MEMORY_LIMIT', '64M');
define('AUTH_KEY', 'vPNcP6QwtutaW872Astd5Ljqz2I4m1rnxVS7xmmOFMq8mG5dr2oOzqzcjXPYJ1nt');
define('SECURE_AUTH_KEY', 'gV2as9npUgVX97PkAjSEpb1QK16djJRJiUch8fLXLc1mduvS7QM3ZAfsX7O45yGk');
define('LOGGED_IN_KEY', 'Mo1TetuzzEaK3Hd5SPsMBS4c1Tp3HcmxKwAedrB9PX04Mb1Lo43qXdkuuNwEawEg');
define('NONCE_KEY', 'jHjQMNo0Asic10AVDPSuBLDvnwvP4zkom0foYTZ7Dn5vdMbg27POjAJb4Rg4w7rA');
define('AUTH_SALT', '2SLjlj4d8O88rkVImBcUYT49cSdwvcWI7eVhNrjU7h0fvw2cftAHw5NsvereHif9');
define('SECURE_AUTH_SALT', 'PW7MOYlvrIlVBaV2NocjFSZ5r9mRmtFRVZhWEBt9qCl1RCF2gONuFnezBlBtdfkJ');
define('LOGGED_IN_SALT', 'NhWICPd3mxhZ5IVzJb56fUTRWnYRvvBD2UyngZy9mnnoyLaGFUGFCOIaS0Rg47fT');
define('NONCE_SALT', 'JYCKi8nPtaKVs4R5wW7NnLueHbsw6kWlZ7LAlT8jtnAunN3Llwsv33f7EsieX5SY');



define( 'AUTOSAVE_INTERVAL', 360 );
